name: AxBoosters
version: '${project.version}'
main: com.artillexstudios.axboosters.AxBoosters
api-version: '1.13'

softdepend:
  - ShopGuiPlus
  - CyberLevels
  - AlonsoLevels
  - TokenManager
  - EconomyShopGui
  - EconomyShopGui-Premium
  - SuperMobCoins
  - TMMobCoins
  - CMI
  - EcoSkills
  - EcoJobs
  - AureliumSkills
  - Jobs
  - RivalHarvesterHoes
  - AxGens
  - CyberLevels
  - BentoBox
  - IridiumSkyBlock
  - Kingdoms
  - SuperiorSkyBlock